language: php

sudo: false

php:
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - stty cols 120

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - composer lint
  - composer style
  - composer phpunit
